services:
  app:
    build: .
    restart: always
    ports:
      - "8081:8081"
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - default

  redis:
    image: redis
    restart: always
    ports:
      - "6179:6379"
    volumes:
      - redis_data:/data
    command: [
      "redis-server",
      "--requirepass", "redis_password",
      "--appendonly", "yes",
      "--maxmemory", "512mb",
      "--maxmemory-policy", "volatile-lru"
    ]
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - default

volumes:
  redis_data:

networks:
  default:
    driver: bridge