version: '3.9'

services:
  app:
    build: .
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      redis:
        condition: service_healthy
    env_file: .env

  redis:
    image: redis
    restart: always
    ports:
      - "6179:6379"
    volumes:
      - redis_data:/data
    env_file: .env
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}", "--appendonly", "yes"]
    healthcheck:
      test: [ "CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  redis_data:

networks:
  default:
    name: redis_network